Repository neurobagel/bagel-cli, pull requests merged in 2024-12, with the labels that each got.

#402 [MNT] Remind about missing value annotation in age parsing error
  bagel/utilities/pheno_utils.py
Labels: pr-patch

#401 [ENH] Allow unrecognized pipeline names and versions in processing status file
  bagel/cli.py
  bagel/mappings.py
  bagel/utilities/derivative_utils.py
  tests/data/README.md
  tests/data/proc_status_no_recognized_pipelines.tsv
  tests/data/proc_status_unrecognized_pipelines.tsv
  tests/integration/test_cli_derivatives.py
  tests/unit/test_derivative_utils.py
Labels: release, pr-patch

#405 [ENH] Add consistent badges
  README.md
Labels: pr-internal

#413 [MNT] Update labels in dependabot.yml
  .github/dependabot.yml
Labels: skip-release
