Repository neurobagel/bagel-cli, pull requests merged in 2024-11, with the labels that each got.

#373 [FIX] Make `pipeline-catalog` submodule available to built Docker image
  .dockerignore
  .github/workflows/build_docker_nightly.yml
  .github/workflows/build_docker_on_release.yml
  Dockerfile
Labels: release, pr-patch

#385 [REF] Refactor utilities
  bagel/cli.py
  bagel/mappings.py
  bagel/utilities/__init__.py
  bagel/utilities/bids_utils.py
  bagel/utilities/derivative_utils.py
  bagel/utilities/file_utils.py
  bagel/utilities/model_utils.py
  bagel/utilities/pheno_utils.py
  tests/integration/test_cli_bids.py
  tests/integration/test_cli_derivatives.py
  tests/integration/test_cli_pheno.py
  tests/test_utility.py
  tests/unit/test_bids_utils.py
  tests/unit/test_derivative_utils.py
  tests/unit/test_file_utils.py
  tests/unit/test_model_utils.py
  tests/unit/test_pheno_utils.py
Labels: pr-internal

#389 [REF] Upgrade codebase to Pydantic>2
  .github/workflows/test.yml
  README.md
  bagel/dictionary_models.py
  bagel/models.py
  bagel/utilities/model_utils.py
  bagel/utilities/pheno_utils.py
  dev_requirements.txt
  requirements.txt
  setup.cfg
  tests/integration/test_cli_pheno.py
  tests/unit/test_model_utils.py
Labels: pr-dependencies

#395 [CI] Remove coveralls
  .github/workflows/test.yml
  README.md
Labels: skip-release
