Repository neurobagel/bagel-cli, pull requests merged in 2024-10, with the labels that each got.

#348 [MNT] Removed build docker nightly workflow file
  .github/workflows/cd.yml
Labels: pr-internal

#360 [INF] Add script to generate `nb_vocab.ttl`
  README.md
  generate_nb_vocab_file.py
Labels: pr-internal

#365 [DOC] Remove usage instructions & update development environment section in README
  README.md
Labels: release, pr-documentation

#368 [DOC] Move pre-commit setup to README.md
  README.md
Labels: pr-documentation
