Repository neurobagel/bagel-cli, pull requests merged in 2024-07, with the labels that each got.

#318 🔄 synced file(s) with neurobagel/workflows
  .autorc
Labels: _bot

#313 [FIX] Handle dashes (/any chars that are not python variable valid) in column names
  bagel/cli.py
  bagel/tests/data/README.md
  bagel/tests/data/example21.json
  bagel/tests/data/example21.tsv
  bagel/tests/test_cli_pheno.py
Labels: release, pr-bug-fix

#319 [CI] Remove required status check from .autorc
  .autorc
Labels: skip-release

#317 [DOC] Note case sensitivity of subject IDs in `bids` IDs check error
  bagel/bids_utils.py
  bagel/tests/test_utility.py
Labels: release, pr-documentation

#322 [CI] Temporarily enable force pushes in release workflow
  .autorc
  .github/workflows/release.yaml
Labels: skip-release

#323 [CI] Change release author to admin
  .autorc
Labels: skip-release

#324 [CI] Try classic PAT in release.yaml
  .autorc
  .github/workflows/release.yaml
Labels: skip-release

#325 [CI] Use `neurobagel-chef-bot` app access token in release.yaml
  .github/workflows/release.yaml
Labels: skip-release

#327 [CI] Remove `protected-branch` plugin (again) now that we're using an app token
  .autorc
  .github/workflows/release.yaml
Labels: skip-release

#328 [DOC] Minor capitalization fix in README.md
  README.md
Labels: skip-release

#330 [CI] Release the CLI
  .github/workflows/release.yaml
Labels: release

#332 🔄 synced file(s) with neurobagel/workflows
  .autorc
  .github/workflows/release.yaml
Labels: _bot
